import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Moon, Sun, Sparkles, ShieldCheck, Download, ArrowRight, CheckCircle2, Clock3, BookOpen, UserRound, LogOut, History, X, LockKeyhole, BarChart3 } from 'lucide-react';
import { signInWithGoogle } from './firebase';
import './styles.css';

type Result = { id?: string; claim: string; createdAt: string; models: { id:string; name:string; verdict:string; response:string; confidence:number; correctness:number; relevance:number; latency:number; tokens:number; sources:{title:string;url:string}[] }[]; recommendation:string; consensus:number; hallucinationRisk:number; summary:string };
type User = { id:string; name:string; email:string };
const api = import.meta.env.VITE_API_URL || 'http://localhost:8080';
const authHeaders = (): Record<string, string> => { const token = localStorage.getItem('veritas_token'); return token ? { Authorization: `Bearer ${token}` } : {}; };

function AuthDialog({ close, complete }: { close:()=>void; complete:(user:User)=>void }) { const [mode,setMode]=useState<'login'|'register'>('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false); const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${api}/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mode==='register'?{name,email,password}:{email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error);localStorage.setItem('veritas_token',d.token);complete(d.user);close()}catch(e){setError(e instanceof Error?e.message:'Could not sign in.')}finally{setBusy(false)}}; const google=async()=>{setBusy(true);setError('');try{const d=await signInWithGoogle();localStorage.setItem('veritas_token',d.token);complete(d.user);close()}catch(e){setError(e instanceof Error?e.message:'Google sign-in failed.')}finally{setBusy(false)}};return <div className="modal-backdrop"><form className="auth-modal" onSubmit={submit}><button type="button" className="close" onClick={close}><X/></button><ShieldCheck/><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p>{mode==='login'?'Log in to save and revisit your fact checks.':'Your history stays private to your account.'}</p><button type="button" className="google-button" disabled={busy} onClick={google}><b>G</b> Continue with Google</button><div className="auth-divider"><span>or use email</span></div>{mode==='register'&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)} /></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Log in':'Create account'} <ArrowRight/></button><button type="button" className="text-button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Need an account? Sign up':'Already have an account? Log in'}</button></form></div>}

function RadarChart({ metrics }: { metrics: readonly (readonly [string, number, string])[] }) { const points = metrics.map(([,value],i)=>{const a=(-90+i*90)*Math.PI/180,r=value*.78;return `${100+Math.cos(a)*r},${100+Math.sin(a)*r}`}).join(' '); return <svg className="radar" viewBox="0 0 200 200" role="img" aria-label="Radar chart comparing analysis quality metrics">{[30,55,80].map(r=><polygon key={r} points={[0,1,2,3].map(i=>{const a=(-90+i*90)*Math.PI/180;return `${100+Math.cos(a)*r},${100+Math.sin(a)*r}`}).join(' ')} />)}{metrics.map(([label,,color],i)=>{const a=(-90+i*90)*Math.PI/180;return <g key={label}><line x1="100" y1="100" x2={100+Math.cos(a)*80} y2={100+Math.sin(a)*80}/><text x={100+Math.cos(a)*93} y={104+Math.sin(a)*93} fill={color}>{label}</text></g>})}<polygon className="radar-fill" points={points}/>{metrics.map(([,value,,],i)=>{const a=(-90+i*90)*Math.PI/180,r=value*.78;return <circle key={i} cx={100+Math.cos(a)*r} cy={100+Math.sin(a)*r} r="3"/>})}</svg> }
function AreaChart({ models }: { models: Result['models'] }) { const width=360,height=185,pad=28; const points=models.map((m,i)=>`${pad+i*((width-pad*2)/Math.max(1,models.length-1))},${height-pad-m.latency/Math.max(1,...models.map(x=>x.latency))*(height-pad*2)}`).join(' '); const area=`${pad},${height-pad} ${points} ${width-pad},${height-pad}`; return <svg className="area" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Area chart comparing model response latency"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad}/><polygon points={area}/><polyline points={points}/>{models.map((m,i)=>{const x=pad+i*((width-pad*2)/Math.max(1,models.length-1)),y=height-pad-m.latency/Math.max(1,...models.map(v=>v.latency))*(height-pad*2);return <g key={m.id}><circle cx={x} cy={y} r="4"/><text x={x} y={height-9}>{m.name.replace('Google ','').replace('Anthropic ','')}</text><text x={x} y={y-9}>{m.latency}ms</text></g>})}</svg> }

function App() { const [dark,setDark]=useState(false),[claim,setClaim]=useState(''),[selected,setSelected]=useState(['gemini','groq','openrouter']),[result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[user,setUser]=useState<User|null>(null),[showAuth,setShowAuth]=useState(false),[showHistory,setShowHistory]=useState(false),[history,setHistory]=useState<Result[]>([]);
 const getHistory=async()=>{try{const r=await fetch(`${api}/api/history`,{headers:authHeaders()});if(r.ok)setHistory(await r.json())}catch{}};
 useEffect(()=>{const token=localStorage.getItem('veritas_token');if(!token)return;fetch(`${api}/api/auth/me`,{headers:authHeaders()}).then(async r=>{if(!r.ok)throw new Error();const d=await r.json();setUser(d.user);getHistory()}).catch(()=>localStorage.removeItem('veritas_token'))},[]);
 const run=async()=>{if(!user){setShowAuth(true);return}setError('');setLoading(true);try{const r=await fetch(`${api}/api/fact-check`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({claim,providers:selected})});const data=await r.json();if(!r.ok)throw new Error(data.error);setResult(data);getHistory()}catch(e){setError(e instanceof Error?e.message:'Could not reach the analysis service.')}finally{setLoading(false)}};
 const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);const download=async()=>{if(!result)return;const r=await fetch(`${api}/api/report`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(result)});const b=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='veritas-report.pdf';a.click();URL.revokeObjectURL(a.href)};const removeHistory=async(id:string)=>{if(!confirm('Delete this fact check from your history?'))return;const r=await fetch(`${api}/api/history/${id}`,{method:'DELETE',headers:authHeaders()});if(r.ok)setHistory(v=>v.filter(x=>x.id!==id))};const clearHistory=async()=>{if(!confirm('Delete all of your saved fact checks? This cannot be undone.'))return;const r=await fetch(`${api}/api/history`,{method:'DELETE',headers:authHeaders()});if(r.ok){setHistory([]);setResult(null)}};const logout=()=>{localStorage.removeItem('veritas_token');setUser(null);setHistory([]);setResult(null)};
 const metrics=useMemo(()=>result?[['Correctness',Math.round(result.models.reduce((a,m)=>a+m.correctness,0)/result.models.length),'#28666e'],['Relevance',Math.round(result.models.reduce((a,m)=>a+m.relevance,0)/result.models.length),'#d56a3a'],['Confidence',result.consensus,'#8b5e3c'],['Low risk',100-result.hallucinationRisk,'#4b7b63']] as const:[],[result]);
 return <main className={dark?'dark':''}><nav><div className="brand"><ShieldCheck/> Veritas</div><div className="links"><a href="#lab">Fact check lab</a><a href="#about">About</a>{user?<><button className="nav-account" onClick={()=>setShowHistory(true)}><History/> History</button><button className="nav-account" onClick={logout}><LogOut/> Log out</button></>:<button className="nav-account" onClick={()=>setShowAuth(true)}><UserRound/> Log in</button>}<button className="icon" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun/>:<Moon/>}</button></div></nav>
 <section className="hero"><span className="eyebrow"><Sparkles/> Evidence, not echo chambers</span><h1>Know what’s <em>worth believing.</em></h1><p>Compare AI analyses, inspect sources, and get a clear, cautious recommendation—in one calm workspace.</p><a className="primary" href="#lab">Start a fact check <ArrowRight/></a><div className="trust"><span>Private account history</span><span>Multi-model analysis</span><span>Source-aware results</span></div></section>
 <section id="lab" className="lab"><div className="section-head"><div><span className="eyebrow">Fact check lab</span><h2>Bring us a claim.</h2></div><p>{user?`Signed in as ${user.name}. Your checks are saved privately.`:'Log in to analyse claims and save your history.'}</p></div><div className="panel"><label>Your claim or question<textarea value={claim} onChange={e=>setClaim(e.target.value)} placeholder="For example: Electric vehicles produce more lifetime emissions than petrol cars." /></label><div className="model-row">{[['gemini','Gemini'],['groq','Groq Llama'],['openrouter','OpenRouter Free'],['openai','OpenAI'],['claude','Claude'],['demo','Evidence baseline']].map(([id,name])=><button className={selected.includes(id)?'model on':'model'} onClick={()=>toggle(id)} key={id}>{selected.includes(id)&&<CheckCircle2/>}{name}</button>)}</div><button className="primary analyze" disabled={loading||claim.trim().length<12||!selected.length} onClick={run}>{loading?'Reviewing evidence…':user?'Find the truth':'Log in to fact check'} <ArrowRight/></button>{error&&<p className="error">{error}</p>}</div></section>
 {result&&<section className="results"><div className="recommend"><span className="eyebrow">Final recommendation</span><div className="score">{result.consensus}<small>%</small></div><div><h2>Model consensus</h2><p>{result.recommendation}</p><div className="pills"><span>Hallucination risk {result.hallucinationRisk}%</span><span>{result.models.length} models compared</span></div></div><button className="outline" onClick={download}><Download/> PDF report</button></div><div className="chartgrid"><div className="card"><h3>Truth ranking</h3>{result.models.map(m=><div className="rank" key={m.id}><b>{m.name}</b><span><i style={{width:`${m.confidence}%`}}/></span><strong>{m.confidence}</strong></div>)}</div><div className="card cube-card"><h3><BarChart3/> 3D quality spectrum</h3><div className="cube-stage">{metrics.map(([label,value,color])=><div className="metric-cube" key={label}><div className="cube-bar" style={{height:`${value*1.3}px`,background:color}}><i/><b>{value}</b></div><span>{label}</span></div>)}</div></div></div><div className="chartgrid advanced-charts"><div className="card"><h3>Quality radar</h3><RadarChart metrics={metrics}/></div><div className="card"><h3>Response speed comparison</h3><AreaChart models={result.models}/></div></div><div className="cards">{result.models.map(m=><article className="answer" key={m.id}><div className="answer-top"><span>{m.name}</span><b className={m.verdict==='Likely true'?'true':m.verdict==='Likely false'?'false':''}>{m.verdict}</b></div><p>{m.response}</p><div className="stats"><span><Clock3/> {m.latency} ms</span><span>{m.tokens} tokens</span></div>{m.sources.length>0&&<div className="sources"><BookOpen/> {m.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title}</a>)}</div>}</article>)}</div></section>}
 <section id="about" className="about"><span className="eyebrow">How Veritas works</span><h2>Transparent AI, grounded decisions.</h2><div><p>Veritas sends your claim to the providers you select, normalizes their assessments, and preserves a clear path back to supporting sources.</p><p>Your encrypted password is never shown or stored as plain text; results are saved in your MongoDB database under your account only.</p></div></section><footer>VERITAS <span>Built for thoughtful verification.</span></footer>{showAuth&&<AuthDialog close={()=>setShowAuth(false)} complete={u=>{setUser(u);getHistory()}} />}{showHistory&&<div className="modal-backdrop"><aside className="history-panel"><button className="close" onClick={()=>setShowHistory(false)}><X/></button><History/><div className="history-title"><h2>Your fact checks</h2>{history.length>0&&<button className="delete-all" onClick={clearHistory}>Delete all</button>}</div>{history.length?history.map(item=><div className="history-row" key={item.id}><button className="history-item" onClick={()=>{setResult(item);setShowHistory(false);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}}><b>{item.claim}</b><span>{new Date(item.createdAt).toLocaleDateString()} · {item.consensus}% confidence</span></button><button className="delete-one" aria-label="Delete this fact check" onClick={()=>item.id&&removeHistory(item.id)}>Delete</button></div>):<p>No saved checks yet. Your first result will appear here.</p>}</aside></div>}</main> }
createRoot(document.getElementById('root')!).render(<App/>);
